### PR TITLE
Release cimhub.lib

### PR DESCRIPTION
**Pull request by poorva1209**
- moved src/main from CIMHub to CIMHub/cimhub.
- release cimhub.lib as a library to be used with GridAPPS-D.
- tested with blazegraph:issue_1175 and resolved few errors in the code. 

To test use:
1. gridappsd/blazegraph:issue_1175
2. goss-gridapps-d with this pull request: https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/1492

---
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/cimhub/12)

### CODE REVIEW

**Comment by temcdrm** [comment]
Looks fine

**Comment by craigpnnl** [comment]
Poorva can you run it the way travis does and see if you can fix the build error...This should just be building the jar file so that should be enough to fix it.

**Comment by poorva1209** [comment]
@craig8 How does travis builds it ?

**Comment by craigpnnl** [comment]
Click on "Checks" tab by the commit line and you can see what its doing

The following is how it is configured to build on travis now.

{
  "language": "java",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "sudo": false,
  "jdk": [
    "oraclejdk8"
  ],
  "install": [
    "./gradlew --version"
  ],
  "script": [
    "./gradlew --continue"
  ]
}

**Comment by poorva1209** [comment]
@craig8 I dont think Powergrid-models was ever building successfully on Travis: https://travis-ci.com/github/GRIDAPPSD/Powergrid-Models/builds.  Running gradlew on local terminal vs Travis  gives different results.

**Review by craig8 — APPROVED** [review]

**Pull request merged**
